In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.6'

# numpy basics
- NumPy는 다차원 배열을 처리할 수 있는 선형대수학(Linear Algebra) 라이브러리입니다.
- 다음이 실행이 안되면 아나콘다프롬프트에서 conda install numpy 를 실행하여 설치합니다.

In [53]:
[{'이름': '홍길동', '나이': 33, '연봉': 30000}, {'이름': '김나나', '나이': 23, '연봉': 60000}, {'이름': '해피', '나이': 40, '연봉': 70000}]
# 연봉순 정렬
# 순수 파이썬으로는 데이터 분석하기 힘들다.
# 일반적으로 실제 데이터는 행과 열로 되어 있음.

# 메모장, 엑셀을 예시로 설명 (테블러 데이터)
# 이름, 나이, 이메일, 연봉
# 홍길동, 20, happy@gmail.com, 40000


# 데이터 분석은 일반적으로 파일 또는 DB의 데이터를 불러와서 분석을 함.

[{'이름': '홍길동', '나이': 33, '연봉': 30000},
 {'이름': '김나나', '나이': 23, '연봉': 60000},
 {'이름': '해피', '나이': 40, '연봉': 70000}]

In [54]:
# key: value, key: value
[{}, {}, {}]

# 3차원 데이터 -> 이미지 : 행렬이 3차원으로 되어 있음. RGB 

# 컴퓨터는 계산을 하려면 모두 숫자로 변환, vector화한다.
# (3,4)      2차원
# (1,3,4)    3차원
# (3,4,5,6)  4차원
# (1,2,3,3,4,5 ...... 1024)  1024차원
# 유사도를 계산하려면, 숫자로 변환 해야함. 

[{}, {}, {}]

# numpy 객체 생성

In [9]:
#리스트를 ndarray로 변환
a = [1,2,3,4]
arr = np.array(a)

In [10]:
type(arr)

numpy.ndarray

In [11]:
len(arr)

4

In [12]:
#튜플을 ndarray로 변환
a = (1,2,3,4)
arr = np.array(a)
arr

array([1, 2, 3, 4])

In [13]:
arr.size

4

In [14]:
a = [1.0, 2, 3, 4, 5]
arr = np.array(a)
arr

array([1., 2., 3., 4., 5.])

In [15]:
a2d = [[1,2,3], [4,5,6], [7,8,9]]
a2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
type(a2d)

list

In [17]:
arr2d = np.array(a2d)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr2d.size

9

In [19]:
arr2d.dtype

dtype('int64')

In [20]:
type(arr2d)

numpy.ndarray

In [21]:
arr2d.shape

(3, 3)

In [22]:
arr2 = np.array([1, 2, 'aa'])
arr2

array(['1', '2', 'aa'], dtype='<U21')

### Save and load data

In [23]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# 파일로 저장하기
np.save('my_array', arr2d)

In [25]:
# 파일로 저장된것 불로오기
arr2d = np.load('my_array.npy')
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in methods and functions

In [26]:
np.zeros(4)

array([0., 0., 0., 0.])

In [27]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
#1차원
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### 특정 값으로, 행렬 만들기

In [30]:
#np.full(shape, 특정값)
np.full((7,),5)

array([5, 5, 5, 5, 5, 5, 5])

In [31]:
np.full((7,2),5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [32]:
np.full((4,2,3),5)

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

### 정수의 배열을 얻고자 할 때

In [33]:
# [0, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9]
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
# numpy로 표현하기
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(5, 30+1)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30])

In [38]:
#np.arange(start,stop,step)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

### 정수 말고 실수를 얻고자 할 때,

In [39]:
# lin -> liner : 실수 값
# np.linspace(start, end, 갯수)
np.linspace(0, 20, 15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

### 개별 문제 내기

In [75]:
#numpy함수를 이용하여 10이하의 짝수와 홀수 각각의 리스트를 생성하고, 이 두가지 리스트를 사용하여 2차원의 데이터를 만들어라.

odd = np.arange(1, 10, 2)
even = np.arange(2, 11, 2)
d_list = np.array([odd,even])
d_list

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

### 1차원의 배열을 얻은 후, "reshape"를 이용하면, 여러 차원으로 생성 가능

In [40]:
#1차원 > reshape(3,3) > 3*3차원으로 변경

In [77]:
#reshape
arr = np.arange(1,21+1)

In [78]:
arr2d = arr.reshape(3,7)
arr2d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [80]:
arr2d.shape

(3, 7)

In [81]:
arr2d = arr.reshape(7, 3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [82]:
arr2d.shape

(7, 3)

In [83]:
arr1d = arr2d.reshape(21)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [85]:
arr2d = arr1d.reshape(-1,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [86]:
arr2d.max()

np.int64(21)

In [87]:
arr2d.min()

np.int64(1)

In [88]:
arr2d.sum()

np.int64(231)

In [89]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [90]:
arr.mean()

np.float64(11.0)

In [91]:
#표준편차
print(arr.std())

6.0553007081949835


In [92]:
arr.var()

np.float64(36.666666666666664)

### 여러단계를 안 거치고, 한번에 원하는 다차원 배열로 만들 수 있다.

In [93]:
# 5부터 19까지
a = np.arange(5,20)
a.size

15

In [94]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [95]:
a.reshape(3,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [96]:
# 5~19까지의 정수로 (3,5) 행렬을 만들고 싶다.
# chain 형식으로 표현
np.arange(5, 20).reshape(3, 5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 랜덤값으로 채워진 배열을 만들 수 있다.

In [97]:
import random

In [98]:
random.random()

0.4946702307740769

In [99]:
# 파이썬의 기본 랜덤 라이브러리는 다차원 배열이 안됨
# 랜덤으로 5개의 숫자를 만들고싶음.
np.random.random(5)

array([0.35390507, 0.49263593, 0.91330145, 0.76582638, 0.97364827])

In [100]:
np.random.random((5,))

array([0.40236064, 0.55277195, 0.30636063, 0.58661997, 0.27492011])

In [101]:
#랜덤 seed
# 0~1사이의 실수로 난수 발생
np.random.random((3,5))

array([[0.45460777, 0.75766525, 0.81757073, 0.25758529, 0.89306511],
       [0.71842202, 0.0206145 , 0.14271733, 0.32530618, 0.8089292 ],
       [0.39899095, 0.42470161, 0.41371868, 0.7871385 , 0.71356575]])

In [106]:
random.seed(4)
random.random()

0.23604808973743452

In [110]:
# 랜덤으로 뽑는 숫자가 나오는 패턴을 일치시키는 방법
# 첫번째 실행에 나온숫자, 두번째 실행에 나온숫자, ... => 패턴
# 하나의 셀에만 적용
random.seed(3)
random.random()

0.23796462709189137

In [112]:
random.random()
#위 아래를 계속 반복 실행하면, 위에는 고정 아래는 변동임을 알 수 있음

0.36995516654807925

In [113]:
# numpy의 seed 고정 방법, 순서대로 실행하는게 중요함.
np.random.seed(3)
np.random.random((3,5))

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695],
       [0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ]])

In [114]:
np.random.random((3,5))

array([[0.59086282, 0.02398188, 0.55885409, 0.25925245, 0.4151012 ],
       [0.28352508, 0.69313792, 0.44045372, 0.15686774, 0.54464902],
       [0.78031476, 0.30636353, 0.22195788, 0.38797126, 0.93638365]])

### 시작값과 끝값을 줄 수 있다
np.random.randint(start, stop, size = shape)

In [115]:
np.random.seed(9)

In [116]:
# np.rnadom.seed(9) 실행하고, 한번만 적용
np.random.randint(1, 45, (7,))

array([29, 23,  2, 23, 41, 28, 34], dtype=int32)

In [117]:
np.random.randint(1, 45, (3,4))

array([[30, 29,  1, 25],
       [11, 30, 43, 13],
       [19, 23,  2, 36]], dtype=int32)

In [118]:
# 1 ~ 9+1
X = np.random.randint(1,100,(3,4))

In [119]:
X.max()

np.int32(81)

In [120]:
X.min()

np.int32(10)

In [121]:
X.mean()

np.float64(41.583333333333336)

In [122]:
X.std()

np.float64(22.687949567018073)

In [123]:
X.var()

np.float64(514.7430555555555)

In [124]:
a = np.array([3,4,5,6,7,8,9,10])
sorted(a.tolist())

[3, 4, 5, 6, 7, 8, 9, 10]

In [125]:
type(a)

numpy.ndarray

In [126]:
# 중앙값 => 데이터를 오름차순으로 정렬한 후, 중간에 있는 값
# 넘파이 객체에는 median이 없음
# 중앙 값이 두개인 경우는 두 값의 평균을 구함.

np.median(a)

np.float64(6.5)

In [127]:
np.random.seed(3)
X = np.random.randint(1,100,(4,5))
X 

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

- axis = 0 : 행 인덱스가 증가하는 방향
- axis = 1 : 열 인덱스가 증가하는 방향

In [128]:
# 각 열별 최대 값을 구하고 싶다.
# [94, 40, 97, 73, 82]
# 가장 큰 값을 구해야 하는 경우

X.max(axis=0)

array([94, 40, 97, 73, 82], dtype=int32)

In [129]:
# 각 행별 최대 값을 구하고 싶다.
# [73, 75, 97, 94]
# 가장 큰 값을 구해야 하는 경우

X.max(axis=1)

array([73, 75, 97, 94], dtype=int32)

In [130]:
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)