In [2]:
import numpy as np

slicing 문제 : 다음의 데이터에서 마지막 값을 추출하는 하는 코드를 작성하시오.<br>
datas = [[40, 20, 75, 42, 11],<br>
       [30, 39, 92, 21, 45],<br>
       [94, 40, 15, 27, 82]]<br>
---------------------<br>
출력 결과: <br>
#array([11, 45, 82])<br>

numpy함수를 이용하여 10이하의 짝수와 홀수 각각의 리스트를 생성하고, 이 두가지 리스트를 사용하여 2차원의 데이터를 만들어라.<br>

---------------------<br>
 출력 결과: <br>
array([[ 1,  3,  5,  7,  9],<br>
       [ 2,  4,  6,  8, 10]])<br>

10부터 30까지 정수로 이루어진 1차원배열을 만든다음 2차원  (7, -1) 형태로 변환하시오.<br>
그리고 최댓값과 최솟값을 구하시오.<br>
---------------------<br>
출력결과 :<br>
[[10 11 12]<br>
 [13 14 15]<br>
 [16 17 18]<br>
 [19 20 21]<br>
 [22 23 24]<br>
 [25 26 27]<br>
 [28 29 30]]<br>

max: 30<br>
min: 10<br>

문제: 위 배열을 3행 4열 형태로 reshape 하시오. 변환된 배열에서 마지막 행만 출력하시오.<br>

datas = [[10, 20, 30, 40, 50, 60],<br>
         [70, 80, 90, 100, 110, 120]]<br>

코드와 그  출력값이 다음과 같을 때 0.6664104711248381을 출력하는 코드를 작성하시오.<br>

random.seed(12)<br>
print(random.random())<br>
print(random.random())<br>
print(random.random())<br>
print(random.random())<br>
-----------------------<br>
0.4745706786885481<br>
0.6574725026572553<br>
0.6664104711248381<br>
0.14260035292536777<br>

seed값을 5로 고정한 후 random.randint(1,11)을 세번 실행했을 때 나오는 값을 구하시오. 

In [12]:
import random
random.seed(5)
random.randint(1,11) #10

10

(1) 1~25까지 step이 3개인 1차원의 배열을 만들고,<br>
(2) reshape을 이용하여 3x3행렬로 만드시오.<br>
----------------------<br>
출력결과<br>
(1)<br>
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])<br>
(2) <br>
array([[ 1,  4,  7],<br>
       [10, 13, 16],<br>
       [19, 22, 25]])<br>

arr의 각 행에서 최댓값만 추출하여 1차원 배열 형태로 출력하시오.<br>
---------------------<br>
import numpy as np<br>
<br>
np.random.seed(11)<br>
arr = np.random.random((4, 5))<br>

np.random.randint(1, 45, (3,4))를 출력하고 리스트 형태로 변환하여 출력하시오.<br>
----------------<br>
결과값 예시: [[2, 27, 6, 41], [27, 23, 3, 3], [34, 30, 43, 25]]<br>

reshape 함수를 사용해 1부터 30까지의 숫자 중 짝수를 찾아 (3,5)의 행렬로 만드시오.<br>
------------------------------<br>
array([[ 2,  4,  6,  8, 10],<br>
       [12, 14, 16, 18, 20],<br>
       [22, 24, 26, 28, 30]])<br>